// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title IZKVerifier
 * @notice ZK proof verification interface
 * @dev Interface for Groth16 proof verification
 *      Actual implementation is auto-generated by snarkjs
 */
interface IZKVerifier {
    /**
     * @notice Groth16 proof verification
     * @param a Proof point A (G1)
     * @param b Proof point B (G2)
     * @param c Proof point C (G1)
     * @param publicInputs Array of public inputs
     * @return valid Whether the proof is valid
     *
     * @dev Expected gas: ~280,000
     *
     * Public inputs structure (MIPS Single Step):
     * - publicInputs[0]: preStateHash (previous state hash)
     * - publicInputs[1]: postStateHash (post state hash)
     * - publicInputs[2]: instruction (MIPS instruction)
     */
    function verifyProof(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[] calldata publicInputs
    ) external view returns (bool valid);
}
